---
- name: sample playbook with handlers
  hosts: redhatservers
  become: true

  vars:
    apache_package: httpd
    apache_service: httpd 
    apache_config_dir: /etc/httpd/conf.d

  handlers:
    - name: restart apache
      service: 
            name: "{{ apache_service }}"
            state: restarted

  tasks:
    - name: Add an environment variable to the remote user's shell
      lineinfile:
        dest: "~/.profile"
        regexp: "^ENV_VAR="
        line: "ENV_VAR=demovalue"
      become: false

    - name: Get the value of an environment variable
      shell: . /home/amit/.profile && echo $ENV_VAR
      register: myvar

    - debug: msg="The variable is {{ myvar.stdout }}"



    - name: Install httpd package
      yum: 
          name: "{{ apache_package }}"
          state: latest

    - name: Copy test config file
      copy: 
          src: test.conf
          dest: "{{ apache_config_dir }}/test.conf"
      notify: restart apache

    - name: Make sure handler flushed immediately
      meta: flush_handlers

    - name: run apache2 service
      service: 
          name: "{{ apache_service }}"
          state: started
    - name: create contents
      copy:
          src: index.html
          dest: /var/www/html/index.html
        