---
- name: sample playbook
  hosts: myservers
  become: true
  tasks:
    - name: Install apache package
      yum: 
          name: apache2
          state: latest
    - name: run apache2 service
      service: 
          name: apache2
          state: started
    - name: stop firewall service
      service:
          name: ufw
          state: stopped
    - name: create contents
      copy:
          src: index.html
          dest: /var/www/html/index.html
        