---
- name: sample playbook
  hosts: ansible_servers
  become: true
  tasks:
    - name: Install httpd package
      yum: 
          name: apache2
          state: latest
    - name: run apache2 service
      service: 
          name: apache2
          state: started
    - name: create contents
      copy:
          src: index.html
          dest: /var/www/html/index.html
        