---
- name: sample playbook with handlers
  hosts: ansible_servers
  become: true

  handlers:
    - name: restart apache
      service: 
            name: apache2
            state: restarted

  tasks:
    - name: Add an environment variable to the remote user's shell
      lineinfile:
        dest: "~/.profile"
        regexp: "^ENV_VAR="
        line: "ENV_VAR=demovalue"
      become: false

    - name: Get the value of an environment variable
      action: shell source ~/.bashrc && echo $ENV_VAR
      register: myvar

    - debug: msg="The variable is {{ myvar.stdout }}"



    - name: Install httpd package
      yum: 
          name: apache2
          state: latest

    - name: Copy test config file
      copy: 
          src: test.conf
          dest: /etc/apache2/conf-enabled/test.conf
      notify: restart apache

    - name: Make sure handler flushed immediately
      meta: flush_handlers

    - name: run apache2 service
      service: 
          name: apache2
          state: started
    - name: create contents
      copy:
          src: index.html
          dest: /var/www/html/index.html
        