---
- name: sample playbook with handlers
  hosts: ansible_servers
  become: true


  handlers:
    - name: another handler
      service:
            name: ufw
            state: stopped
    - name: restart apache
      service: 
            name: apache2
            state: restarted
      notify: another handler

  tasks:
    - name: Install httpd package
      yum: 
          name: apache2
          state: latest

    - name: Copy test config file
      copy: 
          src: test.conf
          dest: /etc/apache2/conf-enabled/test.conf
      notify: restart apache

    - name: Make sure handler flushed immediately
      meta: flush_handlers

    - name: run apache2 service
      service: 
          name: apache2
          state: started
    - name: create contents
      copy:
          src: index.html
          dest: /var/www/html/index.html
        